### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by breisfeld** [cournape/Bento#108]
The documentation link, 
http://cournape.github.com/bento , 
is giving a 404 error.

**Comment by cournape** [comment]
Where did you see that link ?

On Thu, Jun 14, 2012 at 3:37 PM, breisfeld <
reply@reply.github.com

**Comment by breisfeld** [comment]
Near the bottom of https://github.com/cournape/bento and in your recent posting to  
the numpy discussion list entitled "[ANN] Bento 0.1.0"

**Comment by cournape** [comment]
On Thu, Jun 14, 2012 at 3:47 PM, breisfeld <
reply@reply.github.com

> wrote:
> 
> Near the bottom of https://github.com/cournape/bento and in your recent
> posting to
> the numpy discussion list entitled "[ANN] Bento 0.1.0"

Note that it is Bento upper case. I know it is annoying, but for some
reason I screwed up something when I registered the package on github and
never managed to fix it to use lower-case.

David

**Comment by breisfeld** [comment]
Oh, I see. I simply clicked on the hyperlinks. Can't these be fixed?
