### ISSUE TITLE
'module' object has no attribute 'getuid'

### ISSUE THREAD

**Issue by cbrown1** [cournape/Bento#42]
Microsoft Windows XP [Version 5.1.2600](C) Copyright 1985-2001 Microsoft Corp.

C:\Documents and Settings\cabrown4>c:\python27\scripts\bentomaker
  File "c:\python27\lib\site-packages\bentomakerlib\bentomaker.py", line 309, in noexc_main
    ret = main(argv)
  File "c:\python27\lib\site-packages\bentomakerlib\bentomaker.py", line 112, in main
    if os.getuid() == 0:
bentomaker: Error: bentomaker crashed (uncaught exception <type 'exceptions.AttributeError'>: 'modul
e' object has no attribute 'getuid').
Please report this on bento issue tracker:
    http://github.com/cournape/bento/issues

C:\Documents and Settings\cabrown4>

**Comment by cournape** [comment]
BUG: do not use getuid if not available. closed by 5bd3713b158a24d56a5de493bfa486ff533d1202.
