### ISSUE TITLE
Use an "if __name__ == '__main__':" test in the generated scripts

### ISSUE THREAD

**Issue by rkern** [cournape/Bento#45]
Generated scripts should guard their imports with a test for **main**. The reason is that on Windows, multiprocessing will import the main script in order to help initialize the subprocesses because it can't do a real fork. If you do not guard the imports and main() call with a test, then you end up in an infinite loop.

```
diff --git a/bento/commands/script_utils.py b/bento/commands/script_utils.py
index 7ff0484..eadfd8e 100644
--- a/bento/commands/script_utils.py
+++ b/bento/commands/script_utils.py
@@ -14,9 +14,10 @@ SYS_EXECUTABLE = os.path.normpath(sys.executable)

 SCRIPT_TEXT = """\
 # BENTO AUTOGENERATED-CONSOLE SCRIPT
-import sys
-from %(module)s import %(function)s
-sys.exit(%(function)s())
+if __name__ == '__main__':
+    import sys
+    from %(module)s import %(function)s
+    sys.exit(%(function)s())
 """

 _LAUNCHER_MANIFEST = """
```

**Comment by cournape** [comment]
BUG: fix console script to work under multiprocessing. Closed by 1f0ef31f73aad81dff06bfda7565ca7bd6eee03c.

Thanks to Robert Kern for the fix.
