### ISSUE TITLE
allow calling bentomaker from outside directory that contains bento.info

### ISSUE THREAD

**Issue by astraw** [cournape/Bento#50]
I would like to call bentomaker from a CMake-specified build. (Specifically, I am using [ROS](http://www.ros.org) and don't have the ability to change the top-level build system.) What typically happens in CMake is that configure/build/install stages are run from the build (CMAKE_BINARY_DIR) directory. It would be great if I could call bentomaker from CMake by calling it like:

<pre>
# this command is run from the ${CMAKE_BINARY_DIR} directory
bentomaker --bento-dir=${CMAKE_SOURCE_DIR} configure
</pre>

Where the --bento-dir option specifies the directory with the bento.info file. (Another idea is to implement a --bento-info argument specifying the full path to the bento.info file, which in that case might be called something different.)

**Comment by cournape** [comment]
As for the first point, see my comment on your other ticket. 

As for --bento-info option, I did not find a way to do it UI-wise. bentomaker needs to parse the bento.info file to know e.g. configure options, and you would need to pass it to any command. If you have an idea to solve this, then doing the actual code changes would be pretty trivial.

**Comment by cournape** [comment]
I added the global option --bento-info, which defines the source directory (i.e. the parent directory of bento.info defines the source direcotry). You can now do something like:

bentomaker --bento-info=../bento.info configure....

And it will put all the build artefacts into $CWD/build
