### ISSUE TITLE
allow specifying build directory

### ISSUE THREAD

**Issue by astraw** [cournape/Bento#51]
I may want to specify the build directory (to something other than "build"). Looking through the help output of bentomaker, that does not appear possible. It would be great if it were possible, though.

(The context is that of calling bento from within a CMake build. Typically, though CMake's build directory is called the same thing, so coincidentally there's no issue in the default case.)

**Comment by cournape** [comment]
This is not yet possible, but is on the TODO list. Ultimately, I want to be able to build bento packages "out of trees" (where the source directory is outside the current directory), but to do that I need to finish internal refactoring for files handling. This is one of the goal for bento 0.0.6

**Comment by cournape** [comment]
I added the global option --build-directory to bentomaker (e.g. in fde495d1971c0272b13fff8e6599f9e39fdf6619)

bentomaker --build-directory=yomama command....

You need to specify it for every command
