### ISSUE TITLE
bento in distutils mode does not install properly with --prefix & --root

### ISSUE THREAD

**Issue by gour** [cournape/Bento#64]
Hello!

bento-0.05 was capable to properly build itself with:

```
python2 setup.py install --optimize=1 --prefix=/usr --root=/some_root_dir
```

The current version cannot properly handle it, iow. here is the complete log:

```
[gour@atmarama bento-0.0.6] pwd
[gour@atmarama bento-0.0.6] python2 setup.py install --optimize=1 --prefix=/usr --root=/var/abs/local/devel/python-bento/pkg     
running install
running build
running config
/var/abs/local/devel/python-bento/src/bento-0.0.6/bento/core/node_package.py:148: UserWarning: extra source files glob entry '/var/abs/local/devel/python-bento/src/bento-0.0.6/bento.info' did not return any result
  warnings.warn("extra source files glob entry %r did not return any result" % (s,))
```

And I'm ended with:

```
[gour@atmarama usr] tree 
.
├── lib
│   └── python2.7
│       └── site-packages
│           ├── bento
│           │   ├── commands
│           │   │   ├── api.py
 [...]
│           │   └── __version.py
│           └── bentomakerlib
│               ├── bentomaker.py
│               ├── help.py
│               ├── __init__.py
│               └── package_cache.py
└── local
    ├── bin
    │   └── bentomaker
    └── share
        └── bento
            ├── commands
            │   ├── cli.exe
            │   └── wininst
            │       ├── wininst-7.1.exe
            │       ├── wininst-8.0.exe
            │       ├── wininst-9.0-amd64.exe
            │       └── wininst-9.0.exe
            └── parsetab

29 directories, 154 files
```

from where you can see that build process populated ../usr/local directory as well as ../usr/lib.

The above problem is visible when trying to package Bento in Linux distro, but this is required since there is no released Bento with --destdir support.

When we get that, then it makes sense to package Bento by using its recommended way to build it with:

```
python bootstrap.py
./bentomaker install
```

**Comment by cournape** [comment]
Could you try the last master revision ? The install command is now re-implemented from scratch instead of inheriting from distutils.install one, which makes it easier to control things reliably.

**Comment by gour** [comment]
Thanks a lot.

Now it works...the only missing stuff is: 

`error: option --optimize not recognized`

but it's not crucial.

Now, it would be nice to have a new release. ;)

Sincerely,
Gour
