### ISSUE TITLE
Request: Change --list-files to --dry-run

### ISSUE THREAD

**Issue by AphonicChaos** [cournape/Bento#81]
The documentation mentions that if you simply would like to list files to be installed, rather than actually installing them, you would do:
`bentomaker install --list-files`

It might be more intuitive to call the option --dry-run:`
bentomaker install --dry-run`

Mainly because the name suggests that nothing is installed, whereas with --list-files, the only indication I had that such was the case was the documentation itself.

**Comment by cournape** [comment]
--dry-run and -n are now alias for --list-files. I will most likely deprecate --list-files at some point
