### ISSUE TITLE
Scipy build: _cephes.so linked with libraries in wrong order

### ISSUE THREAD

**Issue by pv** [cournape/Bento#82]
Currently, when building Scipy with bento, the `_cephes.so` extension is linked so that `-lgfortran` comes before the `-lsc_*` static libraries. This apparently causes some symbols to go missing; adding `-lgfortran` to the end of the link stanza fixes the issue. I'm not sure if this is a waf or Bento bug.

**Comment by rgommers** [comment]
CC'ing myself

**Comment by cournape** [comment]
Hi Pauli,

I finally took the time to implement a simple ordered link tool in Waf to fix this. Can you try the last bento and scipy master (you will also need a fairly recent waf), and make sure this works for you ?

**Comment by pv** [comment]
Yep, seems to be working now. The `waf_tools`  aren't installed automatically anywhere, though.

**Comment by cournape** [comment]
I indeed forgot to add waf_tools to the package. Should be fixed in 2c7d8c69be437e2b42f776eda4255e885d5ef4b4
